# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcpp_hello_world <- function() {
    .Call('_HighFreq_rcpp_hello_world', PACKAGE = 'HighFreq')
}

#' The function rcpp_mult() multiplies two numbers.
#' @export
rcpp_mult <- function(x, y) {
    .Call('_HighFreq_rcpp_mult', PACKAGE = 'HighFreq', x, y)
}

#' @export
rcpp_mult_vec <- function(x, y) {
    .Call('_HighFreq_rcpp_mult_vec', PACKAGE = 'HighFreq', x, y)
}

#' @export
rcpp_ou_proc <- function(len_gth, eq_price, vol_at, the_ta, r_norm) {
    .Call('_HighFreq_rcpp_ou_proc', PACKAGE = 'HighFreq', len_gth, eq_price, vol_at, the_ta, r_norm)
}

#' @export
roll_sum <- function(re_turns, look_back) {
    .Call('_HighFreq_roll_sum', PACKAGE = 'HighFreq', re_turns, look_back)
}

#' @export
roll_var <- function(re_turns, look_back) {
    .Call('_HighFreq_roll_var', PACKAGE = 'HighFreq', re_turns, look_back)
}

#' @export
roll_wsum <- function(re_turns, wei_ghts) {
    .Call('_HighFreq_roll_wsum', PACKAGE = 'HighFreq', re_turns, wei_ghts)
}

